// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarRatingController from "./bar_rating_controller"
application.register("bar-rating", BarRatingController)

import DuckEventsController from "./duck_events_controller"
application.register("duck-events", DuckEventsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import TypedController from "./typed_controller"
application.register("typed", TypedController)
